### ISSUE TITLE
New variant for ros_sample

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/variants#33]
Hi, I'd like to open discussion here.

currently many sample / example packages are in `desktop` variant, but i do not really see the relationship between them.

for instance,

- We'd like to have `desktop` GUI packages but not `sample / example` packages.
- Edge device w/o GUI, but we want to run `sample / example` packages.

is it worth to have `ros_sample` variant to cover above requirement? any comments are welcome and appreciated.

**Comment by nuclearsandwich** [comment]
This sounds like a reasonable addition to me. However I do think we need to be cautious since I expect we could find valid reasons to create variants for just about every set of ROS packages and I think it makes sense to try and keep the set of official variants boiled down to just those that have near-universal applicability.

The desktop variant in ROS 2 follows the same "batteries-included" model as the desktop metapackage from ROS.
I think that following the guiding force of [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) the desktop variant should contain the roughly analogous set of packages.

For both cases you identify, it may be worth creating a private metapackage, which could be done with ROS tools or using a Debian tool like equivs. I'm interested to hear what other members of @ros2/team think and put this on our meeting agenda for next week.

**Comment by clalancette** [comment]
We discussed this earlier in the week, and here are some of the notes:

1. There was universal agreement that we should keep the examples in the desktop meta-package.  That keeps it compatible with past ROS 1 and ROS 2 releases.
2. While we could add a samples meta-package, in general we think that having some instructions on how to create private meta-packages would be better.  That way people can build their own set of meta-packages that make sense for their individual use-case.  I'll suggest opening an issue on https://github.com/ros2/ros2_documentation so we can track making those instructions.

Let us know if you have questions or additional comments.

**Comment by fujitatomoya** [comment]
@clalancette 

thanks for checking on this 👍 

although i do not really see the logical justification on `desktop incudes samples/examples` but history, i agree with providing an instruction to create private meta-packages sounds great. that is gonna allow user to have full control.

i just created https://github.com/ros2/ros2_documentation/issues/1458 as you told.

**Comment by nuclearsandwich** [comment]
@fujitatomoya if you have a chance could you review https://github.com/ros2/ros2_documentation/pull/1459 which adds the documentation mentioned above. Your feedback is most welcome.
